### ISSUE TITLE
Experience.createEntityXp Missing Parameter

### ISSUE THREAD

**Issue by lucidobservor** [BrisingrAerowing/CraftTweakerUtils#1]
Experience.createEntityXp currently only takes an IWorld and an integer as parameters. This means that you can't actually spawn experience orbs at any particular position, and in fact it's hard to tell if it's working at all.

Solution: Experience.createEntityXp should take an additional IBlockPos parameter, which specifies where the experience orbs should be spawned.

**Comment by asalimod** [comment]
I'm not a dev, so I may be incorrect, but it probably does it the same way as CraftTweaker's IEntityDefinition.createEntity(IWorld) - creates entity without spawning it so you can modify it and use it somewhere else, before you do something to spawn it.

You can spawn EntityXp by setting dimension and position after creation:
```
var exp = Experience.createEntityXp(IWorld, int);
exp.dimension = IWorld.dimension;
exp.position = IBlockPos;
```

There's IEntityDefinition.spawnEntity(IWorld, IBlockPos) method in CrT to spawn entities in an easy way like you want. So still would be nice to see this but with a different method, something like Experience.spawnEntityXp(IWorld, int, IBlockPos);

**Comment by brisingraerowing** [comment]
I was intending on having people spawn stuff in using IEntityDefinition.spawnEntity, but I can add a method to spawn it directly.

**Comment by brisingraerowing** [comment]
Build uploaded to CF. Should be available soon.
