### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by ttamttamS** [BrisingrAerowing/CraftTweakerUtils#2]
Hello, first I want to thank you for this mod, it's quite useful having extended crafttweaker functionality. I've got a few ideas that would be super helpful for my server management that would fit great with this mod:
A server processor: This would only run on a server, somewhat like isRemote() but as a preprocesser.
A number of players zengetter: Would return the number of players on the server.
Thanks so much for your work!

**Comment by brisingraerowing** [comment]
For the preprocessor, I'll do a generic \#onside \[server|client\] system.

**Comment by brisingraerowing** [comment]
Version 0.4 with these features is awaiting approval on Curseforge.
