### ISSUE TITLE
Math.clamp is not documented in the wiki

### ISSUE THREAD

**Issue by nihiltres** [BrisingrAerowing/CraftTweakerUtils#3]
Please make sure to mention Math.clamp on [the Math class wiki page](https://github.com/BrisingrAerowing/CraftTweakerUtils/wiki/Math-Class). It's a very useful method, and people won't discover it unless it's documented. :)

**Comment by brisingraerowing** [comment]
Yeah. I’ve been kind of neglecting the documentation.

**Comment by brisingraerowing** [comment]
Fixed
