### ISSUE TITLE
Explosion Implementation in CraftTweaker

### ISSUE THREAD

**Issue by democat3457** [BrisingrAerowing/CraftTweakerUtils#7]
Hi, is it okay for me to submit a pull request to the main repository that contains the IExplosion class and corresponding method in the IWorld ZenExpansion? I believe it would be useful to integrate the explosions into the existing events and classes from CraftTweaker and to further expand the scope of the main mod, considering it already has explosion events.

**Comment by brisingraerowing** [comment]
If Jared is OK with that, I am.

**Comment by democat3457** [comment]
And it's been released now on the latest CrT build.
