### ISSUE TITLE
Calling getServerCommandSender() results NPE

### ISSUE THREAD

**Issue by TheQKnight** [BrisingrAerowing/CraftTweakerUtils#8]
when trying to use the serverCommandSender through the server command manager, it works, but throws an NPE.

Script im using: https://gist.github.com/TheQKnight/d7ced8b776bf6d732b9bb4d7980f5b78

crafttweaker.log: https://gist.github.com/TheQKnight/df2dd29c073d5c4605be2af1efc6c9b5

**Comment by democat3457** [comment]
Seems as if the server is null

**Comment by democat3457** [comment]
This is probably because the code is being run on the client side as well, which causes the NPE when trying to access the server - try adding a check for whether the world is remote.

**Comment by brisingraerowing** [comment]
Adding the following on line 21 should fix this.

```zenscript
if (event.player.world.isRemote()) return;
```

**Comment by TheQKnight** [comment]
> Adding the following on line 21 should fix this.
> 
> ```zenscript
> if (event.player.world.isRemote()) return;
> ```

Yeah that seemed to do the trick. Thanks.

**Comment by democat3457** [comment]
(Don't forget to close issues when you're done or it's resolved)
